# Generated by Django 5.2 on 2025-04-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_userprofile_calories_burned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dietary_restrictions",
            field=models.TextField(
                blank=True, help_text="Comma‑separated dietary restrictions"
            ),
        ),
    ]
