# Generated by Django 5.2 on 2025-04-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_exerciselog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='duration_minutes',
        ),
    ]
